 version: '3.3'

 services:
   db:
     image: postgres:12.9-alpine
     restart: always
     container_name: postgres
     ports:
       - 5432:5432
     environment:
        POSTGRES_DB: Devmaua
        POSTGRES_PASSWORD: devmaua

   mss_autenticacao:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - PYTHON_ENV=Local
      - DB_USER=postgres
      - DB_PW=DevMaua2022!
      - DB_NAME=DevMaua_DB_dev
      - DB=postgres
    volumes:
      - ./:/app