name: CI

on:
  push:
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  testApp:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Setup Postgres container
      run: |
        docker-compose build db;
        docker-compose up db
    - name: Runs tests
      run: pytest
    - name: Create coverage report
      run: |
        pytest --cov=./
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
