name: Create Jira Issue

on:
  issues:
    types: [opened]

jobs:
  UpdateJira:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Exibe titulo e body
        run: |
          echo Titulo: '${{ github.event.issue.title }}'
          echo body: '${{ github.event.issue.body }}'
      
      - name: Jira Login
        uses: atlassian/gajira-login@v2.0.0
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      
      
      - name: Criar issue no Jira
        id: create
        uses: atlassian/gajira-create@master
        with:
          project: ${{ secrets.JIRA_PROJECT_KEY }}
          issuetype: ${{ secrets.JIRA_ISSUE_TYPE }}
          summary: '${{ github.event.issue.title }}'
          description: '${{ github.event.issue.body }}'

      - name: Comentar o Id da Issue
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Essa issue foi criada no Jira (backlog). 
            A tag da issue é: ${{ steps.create.outputs.issue }}
            ##Lembre-se de: 
             - [ ] Colocar a tag ${{ steps.create.outputs.issue }} no inicio do nome da branch
             - [ ] Colocar a tag ${{ steps.create.outputs.issue }} no inicio da PR
             - [ ] Linkar essa issue (GitHub) com a PR
             |
             Exemplo de nome para branch/PR: ${{ steps.create.outputs.issue }}-${{ github.event.issue.title }}
      
      
      - name: Log created issue
        run: echo "Issue ${{ steps.create.outputs.issue }} was created"


