name: Create Jira Issue

on:
  issues:
    types: [opened]

jobs:
  UpdateJira:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Exibe titulo e body
        run: |
          echo Titulo: ${{ github.event.issue.title }}
          echo body: ${{ github.event.issue.body }}
      
      - name: Jira Login
        uses: atlassian/gajira-login@v2.0.0
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      
      
      - name: Criar issue no Jira
        id: create
        uses: atlassian/gajira-create@master
        with:
          project: ${{ secrets.JIRA_PROJECT_KEY }}
          issuetype: ${{ secrets.JIRA_ISSUE_TYPE }}
          summary: ${{ github.event.issue.title }}
          description: ${{ github.event.issue.body }}



      - name: Log created issue
        run: echo "Issue ${{ steps.create.outputs.issue }} was created"


